name: Build and Release Project

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
    
      - name: Set short commit SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: Zip build
        run: zip -r calabiyauify-names-${{ env.BUILD_DATE }}-git-commit-${{ env.SHORT_SHA }}.zip dist

      # 创建 Release
      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
            tag_name: build-${{ env.BUILD_DATE }}-${{ env.SHORT_SHA }}
            name: calabiyauify-names-${{ env.BUILD_DATE }}-git-commit-${{ env.SHORT_SHA }}.zip
            files: calabiyauify-names-${{ env.BUILD_DATE }}-git-commit-${{ env.SHORT_SHA }}.zip
            overwrite_files: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
